# Generated by Django 4.1.3 on 2023-04-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
